# Generated by Django 5.1.2 on 2024-11-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
