# Generated by Django 5.1.2 on 2024-11-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0006_alter_user_employement_start_alter_user_job_title_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employement_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
