# Generated by Django 5.1.2 on 2024-11-09 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0007_user_employement_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('job_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title_id',
        ),
        migrations.CreateModel(
            name='EmploymentTerms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agreed_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_start_date', models.DateField()),
                ('salary_end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_terms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Payroll.jobtitle'),
        ),
    ]
