# Generated by Django 5.1.2 on 2024-11-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0008_jobtitle_remove_user_job_title_id_employmentterms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentterms',
            options={'ordering': ['-salary_start_date']},
        ),
    ]
