# Generated by Django 5.1.1 on 2024-11-20 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0009_alter_employmentterms_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Payment',
                'verbose_name_plural': 'Salary Payments',
                'ordering': ['-start_date'],
            },
        ),
    ]
