# Generated by Django 5.1.2 on 2024-11-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0015_user_punch_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
