# Generated by Django 5.1.2 on 2024-11-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0018_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='salary_slip/%Y/%m/'),
        ),
    ]
