# Generated by Django 5.1.2 on 2024-11-23 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0019_salarypayment_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='salary_slips/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='SalarySlipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('month', models.DateField(help_text='Month and year of requested salary slip')),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slip_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
