# Generated by Django 5.1.2 on 2024-11-30 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0021_jobposting_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('YEARS', 'Years of Service'), ('SKILL', 'Skill Mastery'), ('PROJECT', 'Project Completion'), ('TRAINING', 'Training Certification'), ('MENTOR', 'Mentorship'), ('INNOVATION', 'Innovation Award')], max_length=20)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievement_icons/')),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('milestone_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('CERTIFICATION', 'Certification'), ('AWARD', 'Award'), ('PROJECT', 'Major Project'), ('TRAINING', 'Training Completion')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('points_earned', models.IntegerField(default=0)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='milestone_attachments/')),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('current_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('endorsed_by', models.ManyToManyField(related_name='endorsed_skills', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payroll.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
